version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo_auth
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: authdb

  auth-service:
    build: .
    container_name: auth_service
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongo:27017/authdb
      JWT_SECRET: super_secret_key

volumes:
  mongo_data:
